import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, watch } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const testVaultPluginDir = join(
  "test-vault",
  ".obsidian",
  "plugins",
  "bases-calendar",
);

const copyToTestVault = {
  name: "copy-to-test-vault",
  setup(build) {
    build.onEnd(() => {
      if (prod || !existsSync(testVaultPluginDir)) return;
      for (const file of ["main.js", "manifest.json", "styles.css"]) {
        if (existsSync(file)) copyFileSync(file, join(testVaultPluginDir, file));
      }
      console.log("Copied build artifacts to test vault");
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: prod ? [] : [copyToTestVault],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  if (existsSync(testVaultPluginDir)) {
    watch("styles.css", () => {
      copyFileSync("styles.css", join(testVaultPluginDir, "styles.css"));
      console.log("Copied styles.css to test vault");
    });
  }
}
